# Generated by Django 5.0.6 on 2025-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
