# Generated by Django 5.0.6 on 2025-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_landlisting_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landowner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='landowner',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='landowner',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photos/'),
        ),
    ]
