# Generated by Django 5.0.6 on 2025-04-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_landowner_address_landowner_gender_landowner_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
