# Generated by Django 5.0.6 on 2025-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_landowner_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
