# Generated by Django 5.0.6 on 2025-05-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
