# Generated by Django 5.0.6 on 2025-05-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_landowner_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='verified',
        ),
        migrations.AddField(
            model_name='landowner',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
