# Generated by Django 5.0.6 on 2025-05-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_landowner_verified_landowner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='status',
        ),
        migrations.AddField(
            model_name='landowner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
