# Generated by Django 5.0.6 on 2025-05-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='landseeker',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_landseekers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landseeker',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
