# Generated by Django 5.0.6 on 2025-05-03 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_landseeker_approved_by_landseeker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='price',
        ),
        migrations.AddField(
            model_name='land',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='land',
            name='land_name',
            field=models.CharField(default='Unknown Land', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='water_availability',
            field=models.CharField(max_length=100),
        ),
    ]
