# Generated by Django 5.0.6 on 2025-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_land_price_land_created_at_land_land_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
