# Generated by Django 5.0.6 on 2025-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_landlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
