# Generated by Django 5.0.6 on 2025-05-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_land_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='land_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='price',
        ),
        migrations.AlterField(
            model_name='land',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(default='To be updated', max_length=255),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.landowner'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='soil_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='water_availability',
            field=models.BooleanField(default=False),
        ),
    ]
