# Generated by Django 5.0.6 on 2025-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_land_land_name_remove_land_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='land_name',
            field=models.CharField(default='Unnamed Land', max_length=100),
        ),
    ]
