# Generated by Django 5.0.6 on 2025-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_land_land_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
